@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Benjamim Thiago",
  "email": "benjamim@rocketseat.com.br",
  "password": "1234567"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "benjamim@rocketseat.com.br",
  "password": "1234567"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 4",
  "content": "Teste 4"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=4
Content-Type: application/json
Authorization: Bearer {{authToken}}