@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Benjamim Thiago",
  "email": "benjamim@rocketseat.com.br",
  "password": "1234567"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "benjamim@rocketseat.com.br",
  "password": "1234567"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 10",
  "content": "Teste 10"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
PUT {{baseUrl}}/questions/2933d75a-9dbd-4857-ba91-d66911a406c5
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 7",
  "content": "Teste 7"
}