version: '3'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the custom Dockerfile
    container_name: nodeapp
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3333:3333"
    tty: true
    command: bash

  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_clean
      #PGDATA: /data/postgres
    # volumes:
    #   - ./data/pg:/data/postgres

